// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/finishy1995/effibot/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/answer",
				Handler: HttpHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/types",
				Handler: TypesHandler(serverCtx),
			},
		},
	)
}
