// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	TypeID            string `form:"type_id"`         // 问题类型
	BeforeParagraphID string `form:"p_id, optional"`  // 上一个关联的会话 ID
	Content           string `form:"content"`         // 内容
	Params            string `form:"params,optional"` // 附加参数
}

type Response struct {
	Code       int32  `json:"code"`        // 状态码
	QuestionID string `json:"question_id"` // 问题 ID
	AnswerID   string `json:"answer_id"`   // 回答 ID
	SessionID  string `json:"session_id"`  // 整个会话的 ID
	Answer     string `json:"answer"`      // 答案
}

type Types struct {
	ID     string   `json:"id"`
	NextID []string `json:"next_id"`
	IsRoot bool     `json:"root"`
	Params []string `json:"params"`
}

type TypesRequest struct {
}

type TypesResponse struct {
	Types []Types `json:"types"`
}
